# Controls the Prometheus server's global configuration
global:
    scrape_interval: 15s # Controls how often Prometheus will scrape targets. Default is every 1 minute.
    evaluation_interval: 15s # Controls how often Prometheus will evaluate rules. The default is every 1 minute.
    external_labels:
      monitor: "todo-monitor"

# Specifies the location of any rules we want the Prometheus server to load.
rule_files:

# Controls what resources Prometheus monitorsa
scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:8080"]
