#!/bin/sh

mysql -h $MYSQL_HOST -u root -P ${MYSQL_PORT} -p$MYSQL_ROOT_PASSWORD -e "CREATE DATABASE IF NOT EXISTS mydb_test;"
mysql -h $MYSQL_HOST -u root -P ${MYSQL_PORT} -p$MYSQL_ROOT_PASSWORD -e "GRANT ALL PRIVILEGES ON mydb_test.* TO 'local_user'@'%'"
export GOOSE_DBSTRING="$MYSQL_USER:$MYSQL_PASSWORD@tcp($MYSQL_HOST:$MYSQL_PORT)/$MYSQL_TEST_DATABASE?parseTime=true"
goose up
export GOOSE_DBSTRING="$MYSQL_USER:$MYSQL_PASSWORD@tcp($MYSQL_HOST:$MYSQL_PORT)/$MYSQL_DATABASE?parseTime=true"
