#!/bin/sh

mysql -h $MYSQL_HOST -u $MYSQL_USER -p $MYSQL_PASSWORD -e "CREATE DATABASE IF NOT EXISTS mydb_test;"
export GOOSE_DBSTRING="$MYSQL_USER:$MYSQL_PASSWORD@tcp($MYSQL_HOST:$MYSQL_PORT)/$MYSQL_TEST_DATABASE?parseTime=true"
goose up
export GOOSE_DBSTRING="$MYSQL_USER:$MYSQL_PASSWORD@tcp($MYSQL_HOST:$MYSQL_PORT)/$MYSQL_DATABASE?parseTime=true"
